[project]
name = "quantum-circuit-gradients"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "qiskit>=2.0.0",
    "numpy",
    "scipy",
    "ddt",
    "matplotlib",
    "qiskit-symb"
]
